---
name: Update S3 Policy

on:

  workflow_dispatch:
   inputs:
     testing_bucket_name:
      description: Enter your bucket
      required: true


jobs:
  update_bucket_policy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Turn Off Block Rule
        run: |
          aws s3api delete-public-access-block --bucket ${{ github.event.inputs.testing_bucket_name }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'

      - name: Update Bucket Policy
        run: | 
          aws s3api put-bucket-policy --bucket ${{ github.event.inputs.testing_bucket_name }} --policy file://storage/pa_bucket_policy.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'
